# Generated by Django 5.2.6 on 2025-09-10 13:29
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- ensure we're in public schema (no-op if already)
                PERFORM set_config('search_path', 'public', true);

                -- create table only if it does not exist
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name   = 'main_news'
                ) THEN
                    CREATE TABLE public.main_news (
                        id uuid PRIMARY KEY,
                        title varchar(255) NOT NULL,
                        content text NOT NULL,
                        category varchar(20) NOT NULL DEFAULT 'update',
                        thumbnail varchar(200),
                        news_views integer NOT NULL DEFAULT 0,
                        created_at timestamp with time zone NOT NULL,
                        is_featured boolean NOT NULL DEFAULT false
                    );
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            -- safe no-op rollback (do not drop data)
            SELECT 1;
            """,
        ),
    ]
